In [9]:
np.savetxt('growth.txt', Particle_list, fmt='%d', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)


In [3]:
import numpy as np
import random


neighborlista=np.array([[0,0,0,2],[0,0,-1,3],[0,-1,0,2],[0,-1,-1,3],[-1,0,0,2],[-1,0,-1,3]])
neighborlistb=np.array([[0,0,0,1],[0,0,0,2],[0,-1,0,1],[0,-1,0,2],[-1,0,0,1],[-1,0,0,2]])
neighborlistc=np.array([[0,0,0,-2],[0,0,0,-1],[0,1,0,-2],[1,0,0,-2],[0,1,0,-1],[1,0,0,-1]])
neighborlistd=np.array([[0,0,0,-2],[0,0,1,-3],[0,1,1,-3],[1,0,1,-3],[0,1,0,-2],[1,0,0,-2]])
def find_neighbor(particle):
    if particle[3]==1:
        return neighborlista+np.tile(particle,(6,1))
    if particle[3]==2:
        return neighborlistb+np.tile(particle,(6,1))
    if particle[3]==3:
        return neighborlistc+np.tile(particle,(6,1))
    if particle[3]==4:
        return neighborlistd+np.tile(particle,(6,1))
class Simulation:
    def __init__(self):
        self.particle_list = []
        self.neighbor_list = []
        self.bond_list = []
        self.events = []
        self.time = 0
    def add_particle(self, particle):
        self.particle_list.append(particle)
        neighbors=find_neighbor(particle)
        
        # ... Update neighbor_list and bond_list

    def insert_one_particle_event(self, particle):
        # ... Define the event, with a rate based on the multiplicity
        rate = 1 / (4 ** self.get_multiplicity(particle))
        self.events.append(('insert', particle, rate))

    def delete_one_particle_event(self, particle):
        # ... Define the event, with a rate based on the system properties
        rate = self.calculate_delete_rate(particle)
        self.events.append(('delete', particle, rate))

    def get_multiplicity(self, particle):
        # ... Implement your logic for getting the multiplicity
        pass

    def calculate_delete_rate(self, particle):
        # ... Implement your logic for calculating the delete rate
        pass

    def execute_event(self, event):
        # ... Implement logic to execute the event, updating the system state accordingly
        pass

    def kmc_step(self):
        total_rate = sum(event[2] for event in self.events)
        dt = -np.log(random.random()) / total_rate
        self.time += dt
        cumulative_rate = 0
        r = random.random() * total_rate
        for event in self.events:
            cumulative_rate += event[2]
            if r < cumulative_rate:
                self.execute_event(event)
                break

    def run(self, steps):
        for _ in range(steps):
            self.kmc_step()
            if steps%10==0:
                np.savetxt('growth%d.txt'%(steps/10), self.particle_list, fmt='%d', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)

# Create the simulation object
sim = Simulation()

# Add the initial particle
sim.add_particle(np.array([0,0,0,1]))

# Run the simulation for a number of steps
sim.run(1000)


NameError: name 'Particle' is not defined

In [5]:
import numpy as np
import random
neighborlista=np.array([[0,0,0,2],[0,0,-1,3],[0,-1,0,2],[0,-1,-1,3],[-1,0,0,2],[-1,0,-1,3]])
neighborlistb=np.array([[0,0,0,1],[0,0,0,2],[0,-1,0,1],[0,-1,0,2],[-1,0,0,1],[-1,0,0,2]])
neighborlistc=np.array([[0,0,0,-2],[0,0,0,-1],[0,1,0,-2],[1,0,0,-2],[0,1,0,-1],[1,0,0,-1]])
neighborlistd=np.array([[0,0,0,-2],[0,0,1,-3],[0,1,1,-3],[1,0,1,-3],[0,1,0,-2],[1,0,0,-2]])
def find_neighbor(particle):
    if particle[3]==1:
        return neighborlista+np.tile(particle,(6,1))
    if particle[3]==2:
        return neighborlistb+np.tile(particle,(6,1))
    if particle[3]==3:
        return neighborlistc+np.tile(particle,(6,1))
    if particle[3]==4:
        return neighborlistd+np.tile(particle,(6,1))


class Simulation:
    def __init__(self):
        self.particle_array = np.empty((0, 4), dtype=int)
        self.neighbor_array = np.empty((0, 4), dtype=int)
        self.multiplicity_array = np.empty((0, 1), dtype=int)
        self.bond_array = np.array([[0]], dtype=int)
        self.events = []
        self.time = 0
        self.g_0=0
        self.g_1=0
    def add_particle(self, i):
        particle=self.neighbor_array[i]
        self.bond_array=np.vstack((self.bond_array,self.multiplicity_array[i]))   
        self.neighbor_array=np.delete(self.neighbor_array,i,axis=0)
        self.multiplicity_array=np.delete(self.multiplicity_array,i,axis=0)
        self.particle_array = np.vstack((self.particle_array, particle))
        neighbors=find_neighbor(particle)
        for i in range(0,6):
            if np.where((self.particle_array == tuple(neighbors[i].tolist())).all(axis=1))[0].size==1:
                self.bond_array[np.where((self.particle_array == tuple(neighbors[i].tolist())).all(axis=1))[0][0]][0]+=1
                
            if np.where((self.neighbor_array == tuple(neighbors[i].tolist())).all(axis=1))[0].size==1:
                self.multiplicity_array[np.where((self.neighbor_array == tuple(neighbors[i].tolist())).all(axis=1))[0][0]][0]+=1
            else:
                self.neighbor_array=np.vstack((self.neighbor_array,neighbors[i]))
                self.multiplicity_array=np.vstack((self.multiplicity_array,np.array([1])))
        # ... Update neighbor_array and bond_array
    def remove_particle(self,i):
        self.neighbor_array=np.vstack((self.neighbor_array,self.particle_array[i]))
        self.multiplicity_array=np.vstack((self.multiplicity_array,self.bond_array[i]))
        vacancy=self.particle_array[i]
        neighbors=find_neighbor(vacancy)
        self.particle_array=np.delete(self.particle_array,i,axis=0)
        self.bond_array=np.delete(self.bond_array,i,axis=0)
        for i in range(0,6):
            if np.where((self.particle_array == tuple(neighbors[i].tolist())).all(axis=1))[0].size==1:
                self.bond_array[np.where((self.particle_array == tuple(neighbors[i].tolist())).all(axis=1))[0][0]][0]-=1
    
            if np.where((self.neighbor_array == tuple(neighbors[i].tolist())).all(axis=1))[0].size==1:
                self.multiplicity_array[np.where((self.neighbor_array == tuple(neighbors[i].tolist())).all(axis=1))[0][0]][0]-=1
                if self.multiplicity_array[np.where((self.neighbor_array == tuple(neighbors[i].tolist())).all(axis=1))[0][0]][0]==0:
                    self.neighbor_array=np.delete(self.neighbor_array,np.where((self.neighbor_array == tuple(neighbors[i].tolist())).all(axis=1))[0][0],axis=0)
                    self.multiplicity_array=np.delete(self.multiplicity_array,np.where((self.neighbor_array == tuple(neighbors[i].tolist())).all(axis=1))[0][0],axis=0) 
        self.particle_array=np.delete(self.particle_array,i,axis=0)
        self.bond_array=np.delete(self.bond_array,i,axis=0)
        
    def insert_one_particle_event(self, i):
        # ... Define the event, with a rate based on the multiplicity
        rate = 1 / (4 ** self.multiplicity_array[i][0])
        self.events.append(('insert', i, rate))

    def delete_one_particle_event(self, i):
        if self.bond_array.shape[0]!=0:
            rate = self.calculate_delete_rate(i)
            self.events.append(('delete', i, rate))
       

    def calculate_delete_rate(self, i):
        g=self.g_0+self.bond_array[i][0]*self.g_1
        return np.exp(-g) / (4 ** self.bond_array[i][0])
        
    
    def execute_event(self, event):
        if event[0]=='insert':
            self.add_particle(event[1])
        if event[0]=='delete':
            self.remove_particle(event[1])

    def kmc_step(self):
        self.events=[]
        for i in range(0,self.neighbor_array.shape[0]):
            self.insert_one_particle_event(i)
        for i in range(0,self.particle_array.shape[0]):
            self.delete_one_particle_event(i)
        total_rate = sum(event[2] for event in self.events)
        rand_number=random.random()
        dt = -np.log(rand_number) / total_rate
        self.time += dt
        cumulative_rate = 0
        r = rand_number * total_rate
        for event in self.events:
            cumulative_rate += event[2]
            if r < cumulative_rate:
                self.execute_event(event)
                break

    def run(self, steps):
        for _ in range(steps):
            self.kmc_step()
            if steps%10==0:
                np.savetxt('growth%d.txt'%(steps/10), self.particle_array, fmt='%d', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
# Create the simulation object
sim = Simulation()

# Add the initial particle
sim.particle_array=np.array([0,0,0,1])
sim.neighbor_array=find_neighbor(np.array([0,0,0,1]))
sim.multiplicity_array=np.array([[1],[1],[1],[1],[1],[1]])
sim.g_0=-5
sim.g_1=7
sim.bond_array=np.empty((0, 1), dtype=int)
# Run the simulation for a number of steps
sim.run(1000)


IndexError: index 0 is out of bounds for axis 0 with size 0

In [41]:
import numpy as np
import random
neighborlista=np.array([[0,0,0,1],[0,0,-1,1],[-1,0,0,1],[-1,0,-1,1],[0,-1,0,1],[0,-1,-1,1]])
neighborlistb=-neighborlista
def find_neighbor(particle):
    if particle[3]==1:
        return neighborlista+np.tile(particle,(6,1))
    if particle[3]==2:
        return neighborlistb+np.tile(particle,(6,1))



class Simulation:
    def __init__(self):
        self.particle_array = np.empty((0, 4), dtype=int)
        self.neighbor_array = np.empty((0, 4), dtype=int)
        self.multiplicity_array = np.empty((0, 1), dtype=int)
        self.bond_array = np.empty((0, 1), dtype=int)
        self.events = []
        self.time = 0
        self.g_0=0
        self.g_1=0
    def add_particle(self, i):
        #add the particle from neighbor array to particle array, update the neighbor array, multiplicity array and bond array accordingly
        particle=self.neighbor_array[i]
        if self.bond_array.shape[0]!=0:
            self.bond_array=np.vstack((self.bond_array,self.multiplicity_array[i]))   
        else:
            self.bond_array=np.vstack((self.bond_array,np.array([0])))
            self.bond_array=np.vstack((self.bond_array,self.multiplicity_array[i]))  
        self.neighbor_array=np.delete(self.neighbor_array,i,axis=0)
        self.multiplicity_array=np.delete(self.multiplicity_array,i,axis=0)
        self.particle_array = np.vstack((self.particle_array, particle))
        neighbors=find_neighbor(particle)
        for i in range(0,6):
            if np.where((self.particle_array == tuple(neighbors[i].tolist())).all(axis=1))[0].size==1:
                self.bond_array[np.where((self.particle_array == tuple(neighbors[i].tolist())).all(axis=1))[0][0]][0]+=1
                
            if np.where((self.neighbor_array == tuple(neighbors[i].tolist())).all(axis=1))[0].size==1:
                self.multiplicity_array[np.where((self.neighbor_array == tuple(neighbors[i].tolist())).all(axis=1))[0][0]][0]+=1
            else:
                self.neighbor_array=np.vstack((self.neighbor_array,neighbors[i]))
                self.multiplicity_array=np.vstack((self.multiplicity_array,np.array([1])))
    def remove_particle(self,i):
        #remove the particle from particle array, update the neighbor array, multiplicity array and bond array accordingly
        if self.bond_array[i][0]!=0:
            self.neighbor_array=np.vstack((self.neighbor_array,self.particle_array[i]))
            self.multiplicity_array=np.vstack((self.multiplicity_array,self.bond_array[i]))
            vacancy=self.particle_array[i]
            neighbors=find_neighbor(vacancy)
            self.particle_array=np.delete(self.particle_array,i,axis=0)
            self.bond_array=np.delete(self.bond_array,i,axis=0)
            for i in range(0,6):
                if np.where((self.particle_array == tuple(neighbors[i].tolist())).all(axis=1))[0].size==1:
                    self.bond_array[np.where((self.particle_array == tuple(neighbors[i].tolist())).all(axis=1))[0][0]][0]-=1
                    index=np.where((self.particle_array == tuple(neighbors[i].tolist())).all(axis=1))[0][0]
                    if self.bond_array[index][0]==0:
                        self.remove_particle(index)
                if np.where((self.neighbor_array == tuple(neighbors[i].tolist())).all(axis=1))[0].size==1:
                    index=np.where((self.neighbor_array == tuple(neighbors[i].tolist())).all(axis=1))[0][0]
                    self.multiplicity_array[index][0]-=1
                    if self.multiplicity_array[index][0]==0:
                        self.neighbor_array=np.delete(self.neighbor_array,index,axis=0)
                        self.multiplicity_array=np.delete(self.multiplicity_array,index,axis=0) 
            self.particle_array=np.delete(self.particle_array,i,axis=0)
            self.bond_array=np.delete(self.bond_array,i,axis=0)
        else:
            self.particle_array=np.delete(self.particle_array,i,axis=0)
            self.bond_array=np.delete(self.bond_array,i,axis=0)
    def insert_one_particle_event(self, i):
        # ... Define the event, with a rate based on the multiplicity
        rate = 1 / (4 ** self.multiplicity_array[i][0])
        self.events.append(('insert', i, rate))

    def delete_one_particle_event(self, i):
        if self.bond_array.shape[0]!=0:
            rate = self.calculate_delete_rate(i)
            self.events.append(('delete', i, rate))
       

    def calculate_delete_rate(self, i):
        g=self.g_0+self.bond_array[i][0]*self.g_1
        return np.exp(-g) / (4 ** self.bond_array[i][0])
        
    
    def execute_event(self, event):
        if event[0]=='insert':
            self.add_particle(event[1])
        if event[0]=='delete':
            self.remove_particle(event[1])

    def kmc_step(self):
        self.events=[]
        for i in range(0,self.neighbor_array.shape[0]):
            self.insert_one_particle_event(i)
        for i in range(0,self.particle_array.shape[0]):
            self.delete_one_particle_event(i)
        total_rate = sum(event[2] for event in self.events)
        rand_number=random.random()
        dt = -np.log(rand_number) / total_rate
        self.time += dt
        cumulative_rate = 0
        r = rand_number * total_rate
        for event in self.events:
            cumulative_rate += event[2]
            if r < cumulative_rate:
                self.execute_event(event)
                break

    def run(self, steps):
        for _ in range(steps):
            self.kmc_step()

# Create the simulation object
sim = Simulation()

# Add the initial particle
sim.particle_array=np.array([0,0,0,1])
sim.neighbor_array=find_neighbor(np.array([0,0,0,1]))
sim.multiplicity_array=np.array([[1],[1],[1],[1],[1],[1]])
sim.g_0=-5
sim.g_1=15
# Run the simulation for a number of steps
sim.run(100)


In [34]:
sim.bond_array

array([[4],
       [7],
       [4],
       [2],
       [2],
       [3],
       [3],
       [2],
       [1],
       [3],
       [2],
       [1],
       [1],
       [1],
       [3],
       [2],
       [1],
       [3],
       [2],
       [2],
       [1],
       [2],
       [1],
       [2],
       [2],
       [3],
       [1],
       [2],
       [1],
       [1],
       [2],
       [1],
       [1],
       [1],
       [2],
       [1],
       [2],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [26]:
sim.particle_array

array([], shape=(0, 4), dtype=int64)

In [42]:
position_array=np.zeros((sim.particle_array.shape[0],3))
atom_array=np.array([[0,0,0],[1.73,1.73/np.sqrt(3),0.94]])
lattice_array=np.array([[3.46,0,0],[3.46/2,3.46*np.sqrt(3)/2,0],[0,0,1.88]])
for i in range(0,sim.particle_array.shape[0]):
    position_array[i]=sim.particle_array[i][0]*lattice_array[0]+sim.particle_array[i][1]*lattice_array[1]+sim.particle_array[i][2]*lattice_array[2]+atom_array[sim.particle_array[i][3]-1]

In [43]:
import plotly.graph_objects as go
import numpy as np

# Helix equation

x, y, z = position_array[0:300,0],position_array[0:300,1],position_array[0:300,2]

fig = go.Figure(data=[go.Scatter3d(x=x, y=y, z=z,
                                   mode='markers')])
fig.show()

In [112]:
sim.particle_array

array([[  0,   0,   0,   1],
       [  0,   0,   0,   3],
       [  0,   0,   0,   2],
       ...,
       [ -1,  17,  -7,   3],
       [-14,   9,  -4,   4],
       [  0,   4,   0,   2]])

In [22]:
neighbor_array.shape

(1, 4)

In [21]:
for i in neighbor_array:
    print(i)

[4 0 0 0]


In [23]:
neighbor_array[-1]

array([4, 0, 0, 0])

In [26]:
np.empty((0, 1), dtype=int)

array([], shape=(0, 1), dtype=int64)

In [27]:
np.full(
  shape=6,
  fill_value=1).shape

(6,)

In [31]:
a=np.array([[1],[1],[1],[1],[1],[1]])

In [51]:
np.vstack((a,np.array([1])))

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [48]:
a

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1]])